{% set python_min = "3.10" %}
{% set name = "ptychodus" %}
{% set version = "1.2" %}

package:
  name: ptychodus-split
  version: {{ version }}

source:
  url: https://github.com/AdvancedPhotonSource/ptychodus/archive/refs/tags/v{{ version }}.zip
  sha256: 3a09c9c7562f27e20806a96ae8e2a0a90d353041cf0c2e7750cc2aa4b3839e58

build:
  number: 0

outputs:
  # all optional packages
  - name: ptychodus-all

    build:
      noarch: generic

    requirements:
      run:
        - {{ pin_subpackage('ptychodus', exact=True) }}

    test:
      imports:
        - ptychodus
      requires:
        - pip
      commands:
        - pip check
        - ptychodus --version

  # with QT
  - name: ptychodus

    build:
      noarch: generic

    requirements:
      run:
        - {{ pin_subpackage('ptychodus-core', exact=True) }}
        - pyqt

    test:
      imports:
        - ptychodus
      requires:
        - pip
      commands:
        - pip check
        - ptychodus --version

  # ptychodus without QT (headless) without optional packages
  - name: ptychodus-core

    script: build-core.sh

    build:
      noarch: python
      entry_points:
        - convert-to-ptychodus = ptychodus.convert_to_ptychodus:main
        - ptychodus = ptychodus.__main__:main
        - ptychodus-bdp = ptychodus.ptychodus_bdp:main

    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools >=64
        - setuptools_scm >=8
        - setuptools_scm_git_archive
        - wheel
      run:
        - h5py
        - hdf5plugin
        - matplotlib-base
        - numpy
        - psutil
        - python >={{ python_min }}
        - requests
        - scikit-image
        - scipy
        - tifffile
        - watchdog
      run_constrained:
        - gladier
        - gladier-tools >=0.5.4
        - ptychonn =0.3.*,>=0.3.7
        - pyqt =5.*
        - tike >=0.25.3,<0.26

    test:
      imports:
        - ptychodus
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
        - ptychodus --version

about:
  home: https://github.com/AdvancedPhotonSource/ptychodus
  summary: Ptychodus is a ptychography data analysis application.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/AdvancedPhotonSource/ptychodus

extra:
  recipe-maintainers:
    - AdvancedPhotonSource/ptychodus
    - carterbox
    - stevehenke
